vector-absolute.o
vector-add.o
vector-add_scalar.o
vector-angle.o
vector-angle_norm.o
vector-dist.o
vector-div.o
vector-div_scalar.o
vector-dot_product.o
vector-magnitude.o
vector-mult.o
vector-mult_scalar.o
vector-negate.o
vector-normalize.o
vector-sub.o
vector-sub_scalar.o
vector-sum.o
vector-zero.o
vector.o
